"""Deterministic LAMMPS input/data generation for the DeepMD pair style.

Preparation only: running `lmp` is gated on owner approval of an MD backend,
so this adapter never executes a binary.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from mlip_research_agent.skills.base import Skill, SkillContext, expect_inputs, register_skill
from mlip_research_agent.skills.external_adapters.common import (
    load_structure_set,
    upstream_provenance,
    write_registered_json,
    write_registered_text,
)
from mlip_research_agent.skills.external_adapters.lammps.schema import (
    LAMMPSPrepareInput,
    LAMMPSPrepareOutput,
)
from mlip_research_agent.skills.external_adapters.lammps.validators import (
    finite_structure_records,
    require_orthorhombic,
    structure_index,
)

UPSTREAM_PATH = "molecular-dynamics/lammps-deepmd"
INPUT_FILE = "in.lammps"
DATA_FILE = "data.lammps"
PROVENANCE_FILE = "lammps_provenance.json"


def _atomic_mass(symbol: str) -> float:
    from ase.data import atomic_masses, atomic_numbers

    return float(atomic_masses[atomic_numbers[symbol]])


def render_data_file(record: Any, type_map: dict[str, int]) -> str:
    lines = [
        "# generated by external_lammps (prepare-only)",
        "",
        f"{len(record.symbols)} atoms",
        f"{len(type_map)} atom types",
        "",
        f"0.0 {record.cell[0][0]:.10f} xlo xhi",
        f"0.0 {record.cell[1][1]:.10f} ylo yhi",
        f"0.0 {record.cell[2][2]:.10f} zlo zhi",
        "",
        "Masses",
        "",
    ]
    for symbol, type_id in sorted(type_map.items(), key=lambda item: item[1]):
        lines.append(f"{type_id} {_atomic_mass(symbol):.6f}  # {symbol}")
    lines.extend(["", "Atoms  # atomic", ""])
    for index, (symbol, position) in enumerate(
        zip(record.symbols, record.positions, strict=True), start=1
    ):
        coordinates = " ".join(f"{value:.10f}" for value in position)
        lines.append(f"{index} {type_map[symbol]} {coordinates}")
    return "\n".join(lines) + "\n"


def render_input_deck(params: LAMMPSPrepareInput, type_map: dict[str, int]) -> str:
    ordered_symbols = " ".join(
        symbol for symbol, _ in sorted(type_map.items(), key=lambda item: item[1])
    )
    return (
        "# generated by external_lammps (prepare-only; execution gated)\n"
        "units metal\n"
        "boundary p p p\n"
        "atom_style atomic\n"
        f"read_data {DATA_FILE}\n"
        f"pair_style deepmd {params.model_filename}\n"
        f"pair_coeff * * {ordered_symbols}\n"
        f"timestep {params.timestep_ps:.6f}\n"
        f"fix integrate all {params.ensemble}\n"
        "thermo 1\n"
        f"run {params.n_steps}\n"
    )


@register_skill
class ExternalLAMMPSPrepareSkill(Skill):
    """Render deterministic LAMMPS DeepMD inputs for one structure."""

    name = "external_lammps"
    input_model = LAMMPSPrepareInput
    output_model = LAMMPSPrepareOutput
    cost_class = "trivial"

    def run(self, inputs: BaseModel, ctx: SkillContext) -> BaseModel:
        params = expect_inputs(inputs, LAMMPSPrepareInput)
        structures = load_structure_set(ctx, params.structures_path)
        finite_structure_records(structures.systems)
        record = structure_index(structures.systems, params.structure_index)
        require_orthorhombic(record.cell)
        type_map = {
            symbol: index + 1 for index, symbol in enumerate(sorted(set(record.symbols)))
        }
        data_artifact = write_registered_text(
            ctx, DATA_FILE, render_data_file(record, type_map), "external_lammps_data"
        )
        deck_artifact = write_registered_text(
            ctx,
            INPUT_FILE,
            render_input_deck(params, type_map),
            "external_lammps_input_deck",
        )
        provenance_artifact = write_registered_json(
            ctx,
            PROVENANCE_FILE,
            {
                **upstream_provenance(UPSTREAM_PATH),
                "tool": "lammps + deepmd pair style (input preparation only)",
                "execution": "forbidden until an MD backend is owner-approved",
                "input": params.model_dump(mode="json"),
                "type_map": type_map,
                "input_deck_artifact": deck_artifact.artifact_id,
                "data_file_artifact": data_artifact.artifact_id,
            },
            "external_adapter_provenance",
        )
        return LAMMPSPrepareOutput(
            input_deck_artifact=deck_artifact.artifact_id,
            input_deck_path=deck_artifact.relative_path,
            data_file_artifact=data_artifact.artifact_id,
            data_file_path=data_artifact.relative_path,
            provenance_artifact=provenance_artifact.artifact_id,
            provenance_path=provenance_artifact.relative_path,
            n_atoms=len(record.symbols),
            type_map=type_map,
        )
